### PR TITLE
Add snake graphic

### PR DESCRIPTION
**Pull request by rpeikes**
I made the snake look like a worm

### CODE REVIEW

**Comment by andrewoid** [comment]
That's not the only change in the PR though. A PR should have one change and one change only in it.

**Comment by rpeikes** [comment]
Oh I see. I thought that when I changed branches it would separate that, but clearly not. Can we discuss how/if it's possible to work from multiple branches from same computer in class tomorrow?

**Comment by andrewoid** [comment]
It depends on WHERE you branch from.
If you branch from master, then your changes will be against master when you open a PR
If you branch from another branch, then when you open a PR against master the PR will have changes from both branches.

**Comment by rpeikes** [comment]
Ah got it. So can I just delete this branch? I thought it would be fun to play around with the snake colors since no one was assigned that task, but now it's just giving me problem in the command line when I want to commit code to the AddFoodGraphics branch...

**Comment by rpeikes** [comment]
I'm confused. Even after committing and pushing here, it still won't let me switch branches back to AddFoodGraphics...

**Comment by rpeikes** [comment]
Re the food--I can't understand why it can't read the png file. I tried it with two different files so presumably it's not the file itself...

**Comment by rpeikes** [comment]
Is it because the image is too large? I saw online that if its over 50MB, it will throw an exception, but I don't know how to remedy that

**Review by andrewoid — CHANGES_REQUESTED** [review]
This PR does more than just change the way the snake is displayed

**Pull request closed without merging**
