### PR TITLE
Add food graphics

### PR DESCRIPTION
**Pull request by rpeikes**
I changed the food from a gray square to a flashing circle

### CODE REVIEW

**Comment by andrewoid** [comment]
You were supposed to add in images, not s flashing circle.

**Comment by rpeikes** [comment]
Images meaning a drawing in swing or like a png or gif etc?

**Comment by andrewoid** [comment]
Png

**Comment by rpeikes** [comment]
Should I be using drawImage or should I do away with the Graphics object?

**Comment by andrewoid** [comment]
drawImage

**Pull request closed without merging**
